### ISSUE TITLE
Could not match the transform.json provided in instant-DexNerf/data/nerf/canister

### ISSUE THREAD

**Issue by JiayingGaoo** [salykovaa/instant-DexNerf#3]
I run the colmap2nerf.py for canister dataset to obtain a new transform.json. However, it seems different from the one provided  here(https://github.com/salykovaa/instant-DexNerf/blob/main/data/nerf/canister/transforms.json).  I cannot sure if sth wrong? Thanks a lot!

**Comment by salykova** [comment]
@JiayingGaoo 
should I close it?

**Comment by JiayingGaoo** [comment]
take the image 000013.png as an example:
My transforms.json is:      
      "file_path": "./..\\nerf_dataset\\canister\\rgb/000013.png",
      "sharpness": 225.64088499731545,
      "transform_matrix": [
        [
          0.9252319058970376,
          -0.010225193323225157,
          -0.3792642426905294,
          -1.3043773691739173
        ],
        [
          -0.371394723155427,
          -0.228699751520274,
          -0.8998679810286253,
          -2.8522108483541735
        ],
        [
          -0.07753631399245105,
          0.9734433055596362,
          -0.21539788982077182,
          -0.7281496808104705
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ]
The sample transform.json is:
      "file_path": "rgb\\000013.png",
      "sharpness": 175.90436756731887,
      "transform_matrix": [
        [
          -0.3977842298110647,
          0.1687089575879806,
          -0.9018342387286009,
          0.557278002598
        ],
        [
          -0.023888090098159065,
          -0.9845193466753834,
          -0.17364047677122615,
          -0.913837386469
        ],
        [
          -0.9171679593537274,
          -0.04752834576811476,
          0.39565640483058817,
          -0.13816108866899995
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ]

**Comment by JiayingGaoo** [comment]
> @JiayingGaoo should I close it?

yes, thanks! I just want to reproduce the sample results.

**Comment by salykova** [comment]
Hi @JiayingGaoo 
You should run ```ours2nerf.py``` instead of ```colmap2nerf.py``` The poses, provided by us, are not in colmap format. check readme

**Comment by JiayingGaoo** [comment]
> Hi @JiayingGaoo You should run `ours2nerf.py` instead of `colmap2nerf.py` The poses, provided by us, are not in colmap format. check readme

It works, thanks a lot!
