### ISSUE TITLE
How to evaluate the depth map error?

### ISSUE THREAD

**Issue by kevinchan04** [salykovaa/instant-DexNerf#4]
Hi, thank you for your code! May I ask how to evaluate the depth map error in your case?

**Comment by salykova** [comment]
Hi @kevinchan04,

Sorry for the late reply. I uploaded ground thruth depth maps for the canister scene. [gt_depth.zip](https://github.com/salykovaa/instant-DexNerf/blob/main/data/nerf/canister/gt_depth.zip)
